/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class extVelocity_lcmt implements lcm.lcm.LCMEncodable
{
    public float linear[];
    public float angular[];
 
    public extVelocity_lcmt()
    {
        linear = new float[3];
        angular = new float[3];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x6abf27a673175068L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.extVelocity_lcmt.class))
            return 0L;
 
        classes.add(lcmtypes.extVelocity_lcmt.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.linear[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.angular[a]); 
        }
 
    }
 
    public extVelocity_lcmt(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public extVelocity_lcmt(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.extVelocity_lcmt _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.extVelocity_lcmt o = new lcmtypes.extVelocity_lcmt();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.linear = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.linear[a] = ins.readFloat();
        }
 
        this.angular = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.angular[a] = ins.readFloat();
        }
 
    }
 
    public lcmtypes.extVelocity_lcmt copy()
    {
        lcmtypes.extVelocity_lcmt outobj = new lcmtypes.extVelocity_lcmt();
        outobj.linear = new float[(int) 3];
        System.arraycopy(this.linear, 0, outobj.linear, 0, 3); 
        outobj.angular = new float[(int) 3];
        System.arraycopy(this.angular, 0, outobj.angular, 0, 3); 
        return outobj;
    }
 
}

