/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class MHPC_Command_lcmt implements lcm.lcm.LCMEncodable
{
    public int N_mpcsteps;
    public float mpc_times[];
    public float torque[][];
    public float eul[][];
    public float pos[][];
    public float qJ[][];
    public float vWorld[][];
    public float eulrate[][];
    public float qJd[][];
    public float GRF[][];
    public float feedback[][];
    public float Qu[][];
    public float Quu[][];
    public float Qux[][];
    public int contacts[][];
    public float statusTimes[][];
 
    public MHPC_Command_lcmt()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x89db73fa18a9429fL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.MHPC_Command_lcmt.class))
            return 0L;
 
        classes.add(lcmtypes.MHPC_Command_lcmt.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeInt(this.N_mpcsteps); 
 
        for (int a = 0; a < this.N_mpcsteps; a++) {
            outs.writeFloat(this.mpc_times[a]); 
        }
 
        for (int a = 0; a < this.N_mpcsteps; a++) {
            for (int b = 0; b < 12; b++) {
                outs.writeFloat(this.torque[a][b]); 
            }
        }
 
        for (int a = 0; a < this.N_mpcsteps; a++) {
            for (int b = 0; b < 3; b++) {
                outs.writeFloat(this.eul[a][b]); 
            }
        }
 
        for (int a = 0; a < this.N_mpcsteps; a++) {
            for (int b = 0; b < 3; b++) {
                outs.writeFloat(this.pos[a][b]); 
            }
        }
 
        for (int a = 0; a < this.N_mpcsteps; a++) {
            for (int b = 0; b < 12; b++) {
                outs.writeFloat(this.qJ[a][b]); 
            }
        }
 
        for (int a = 0; a < this.N_mpcsteps; a++) {
            for (int b = 0; b < 3; b++) {
                outs.writeFloat(this.vWorld[a][b]); 
            }
        }
 
        for (int a = 0; a < this.N_mpcsteps; a++) {
            for (int b = 0; b < 3; b++) {
                outs.writeFloat(this.eulrate[a][b]); 
            }
        }
 
        for (int a = 0; a < this.N_mpcsteps; a++) {
            for (int b = 0; b < 12; b++) {
                outs.writeFloat(this.qJd[a][b]); 
            }
        }
 
        for (int a = 0; a < this.N_mpcsteps; a++) {
            for (int b = 0; b < 12; b++) {
                outs.writeFloat(this.GRF[a][b]); 
            }
        }
 
        for (int a = 0; a < this.N_mpcsteps; a++) {
            for (int b = 0; b < 432; b++) {
                outs.writeFloat(this.feedback[a][b]); 
            }
        }
 
        for (int a = 0; a < this.N_mpcsteps; a++) {
            for (int b = 0; b < 12; b++) {
                outs.writeFloat(this.Qu[a][b]); 
            }
        }
 
        for (int a = 0; a < this.N_mpcsteps; a++) {
            for (int b = 0; b < 144; b++) {
                outs.writeFloat(this.Quu[a][b]); 
            }
        }
 
        for (int a = 0; a < this.N_mpcsteps; a++) {
            for (int b = 0; b < 432; b++) {
                outs.writeFloat(this.Qux[a][b]); 
            }
        }
 
        for (int a = 0; a < this.N_mpcsteps; a++) {
            for (int b = 0; b < 4; b++) {
                outs.writeInt(this.contacts[a][b]); 
            }
        }
 
        for (int a = 0; a < this.N_mpcsteps; a++) {
            for (int b = 0; b < 4; b++) {
                outs.writeFloat(this.statusTimes[a][b]); 
            }
        }
 
    }
 
    public MHPC_Command_lcmt(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public MHPC_Command_lcmt(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.MHPC_Command_lcmt _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.MHPC_Command_lcmt o = new lcmtypes.MHPC_Command_lcmt();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.N_mpcsteps = ins.readInt();
 
        this.mpc_times = new float[(int) N_mpcsteps];
        for (int a = 0; a < this.N_mpcsteps; a++) {
            this.mpc_times[a] = ins.readFloat();
        }
 
        this.torque = new float[(int) N_mpcsteps][(int) 12];
        for (int a = 0; a < this.N_mpcsteps; a++) {
            for (int b = 0; b < 12; b++) {
                this.torque[a][b] = ins.readFloat();
            }
        }
 
        this.eul = new float[(int) N_mpcsteps][(int) 3];
        for (int a = 0; a < this.N_mpcsteps; a++) {
            for (int b = 0; b < 3; b++) {
                this.eul[a][b] = ins.readFloat();
            }
        }
 
        this.pos = new float[(int) N_mpcsteps][(int) 3];
        for (int a = 0; a < this.N_mpcsteps; a++) {
            for (int b = 0; b < 3; b++) {
                this.pos[a][b] = ins.readFloat();
            }
        }
 
        this.qJ = new float[(int) N_mpcsteps][(int) 12];
        for (int a = 0; a < this.N_mpcsteps; a++) {
            for (int b = 0; b < 12; b++) {
                this.qJ[a][b] = ins.readFloat();
            }
        }
 
        this.vWorld = new float[(int) N_mpcsteps][(int) 3];
        for (int a = 0; a < this.N_mpcsteps; a++) {
            for (int b = 0; b < 3; b++) {
                this.vWorld[a][b] = ins.readFloat();
            }
        }
 
        this.eulrate = new float[(int) N_mpcsteps][(int) 3];
        for (int a = 0; a < this.N_mpcsteps; a++) {
            for (int b = 0; b < 3; b++) {
                this.eulrate[a][b] = ins.readFloat();
            }
        }
 
        this.qJd = new float[(int) N_mpcsteps][(int) 12];
        for (int a = 0; a < this.N_mpcsteps; a++) {
            for (int b = 0; b < 12; b++) {
                this.qJd[a][b] = ins.readFloat();
            }
        }
 
        this.GRF = new float[(int) N_mpcsteps][(int) 12];
        for (int a = 0; a < this.N_mpcsteps; a++) {
            for (int b = 0; b < 12; b++) {
                this.GRF[a][b] = ins.readFloat();
            }
        }
 
        this.feedback = new float[(int) N_mpcsteps][(int) 432];
        for (int a = 0; a < this.N_mpcsteps; a++) {
            for (int b = 0; b < 432; b++) {
                this.feedback[a][b] = ins.readFloat();
            }
        }
 
        this.Qu = new float[(int) N_mpcsteps][(int) 12];
        for (int a = 0; a < this.N_mpcsteps; a++) {
            for (int b = 0; b < 12; b++) {
                this.Qu[a][b] = ins.readFloat();
            }
        }
 
        this.Quu = new float[(int) N_mpcsteps][(int) 144];
        for (int a = 0; a < this.N_mpcsteps; a++) {
            for (int b = 0; b < 144; b++) {
                this.Quu[a][b] = ins.readFloat();
            }
        }
 
        this.Qux = new float[(int) N_mpcsteps][(int) 432];
        for (int a = 0; a < this.N_mpcsteps; a++) {
            for (int b = 0; b < 432; b++) {
                this.Qux[a][b] = ins.readFloat();
            }
        }
 
        this.contacts = new int[(int) N_mpcsteps][(int) 4];
        for (int a = 0; a < this.N_mpcsteps; a++) {
            for (int b = 0; b < 4; b++) {
                this.contacts[a][b] = ins.readInt();
            }
        }
 
        this.statusTimes = new float[(int) N_mpcsteps][(int) 4];
        for (int a = 0; a < this.N_mpcsteps; a++) {
            for (int b = 0; b < 4; b++) {
                this.statusTimes[a][b] = ins.readFloat();
            }
        }
 
    }
 
    public lcmtypes.MHPC_Command_lcmt copy()
    {
        lcmtypes.MHPC_Command_lcmt outobj = new lcmtypes.MHPC_Command_lcmt();
        outobj.N_mpcsteps = this.N_mpcsteps;
 
        outobj.mpc_times = new float[(int) N_mpcsteps];
        if (this.N_mpcsteps > 0)
            System.arraycopy(this.mpc_times, 0, outobj.mpc_times, 0, (int) this.N_mpcsteps); 
        outobj.torque = new float[(int) N_mpcsteps][(int) 12];
        for (int a = 0; a < this.N_mpcsteps; a++) {
            System.arraycopy(this.torque[a], 0, outobj.torque[a], 0, 12);        }
 
        outobj.eul = new float[(int) N_mpcsteps][(int) 3];
        for (int a = 0; a < this.N_mpcsteps; a++) {
            System.arraycopy(this.eul[a], 0, outobj.eul[a], 0, 3);        }
 
        outobj.pos = new float[(int) N_mpcsteps][(int) 3];
        for (int a = 0; a < this.N_mpcsteps; a++) {
            System.arraycopy(this.pos[a], 0, outobj.pos[a], 0, 3);        }
 
        outobj.qJ = new float[(int) N_mpcsteps][(int) 12];
        for (int a = 0; a < this.N_mpcsteps; a++) {
            System.arraycopy(this.qJ[a], 0, outobj.qJ[a], 0, 12);        }
 
        outobj.vWorld = new float[(int) N_mpcsteps][(int) 3];
        for (int a = 0; a < this.N_mpcsteps; a++) {
            System.arraycopy(this.vWorld[a], 0, outobj.vWorld[a], 0, 3);        }
 
        outobj.eulrate = new float[(int) N_mpcsteps][(int) 3];
        for (int a = 0; a < this.N_mpcsteps; a++) {
            System.arraycopy(this.eulrate[a], 0, outobj.eulrate[a], 0, 3);        }
 
        outobj.qJd = new float[(int) N_mpcsteps][(int) 12];
        for (int a = 0; a < this.N_mpcsteps; a++) {
            System.arraycopy(this.qJd[a], 0, outobj.qJd[a], 0, 12);        }
 
        outobj.GRF = new float[(int) N_mpcsteps][(int) 12];
        for (int a = 0; a < this.N_mpcsteps; a++) {
            System.arraycopy(this.GRF[a], 0, outobj.GRF[a], 0, 12);        }
 
        outobj.feedback = new float[(int) N_mpcsteps][(int) 432];
        for (int a = 0; a < this.N_mpcsteps; a++) {
            System.arraycopy(this.feedback[a], 0, outobj.feedback[a], 0, 432);        }
 
        outobj.Qu = new float[(int) N_mpcsteps][(int) 12];
        for (int a = 0; a < this.N_mpcsteps; a++) {
            System.arraycopy(this.Qu[a], 0, outobj.Qu[a], 0, 12);        }
 
        outobj.Quu = new float[(int) N_mpcsteps][(int) 144];
        for (int a = 0; a < this.N_mpcsteps; a++) {
            System.arraycopy(this.Quu[a], 0, outobj.Quu[a], 0, 144);        }
 
        outobj.Qux = new float[(int) N_mpcsteps][(int) 432];
        for (int a = 0; a < this.N_mpcsteps; a++) {
            System.arraycopy(this.Qux[a], 0, outobj.Qux[a], 0, 432);        }
 
        outobj.contacts = new int[(int) N_mpcsteps][(int) 4];
        for (int a = 0; a < this.N_mpcsteps; a++) {
            System.arraycopy(this.contacts[a], 0, outobj.contacts[a], 0, 4);        }
 
        outobj.statusTimes = new float[(int) N_mpcsteps][(int) 4];
        for (int a = 0; a < this.N_mpcsteps; a++) {
            System.arraycopy(this.statusTimes[a], 0, outobj.statusTimes[a], 0, 4);        }
 
        return outobj;
    }
 
}

