/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class mhpc_plan_2D_lcmt implements lcm.lcm.LCMEncodable
{
    public float Pos[][];
    public float rpy[];
    public float q_knee[][];
    public float q_hip[][];
    public float Vel[][];
    public float omega[];
    public float qd_knee[][];
    public float qd_hip[][];
    public float microtime[];
 
    public mhpc_plan_2D_lcmt()
    {
        Pos = new float[2][100];
        rpy = new float[100];
        q_knee = new float[2][100];
        q_hip = new float[2][100];
        Vel = new float[2][100];
        omega = new float[100];
        qd_knee = new float[2][100];
        qd_hip = new float[2][100];
        microtime = new float[100];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x8bab580a55a27bd5L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.mhpc_plan_2D_lcmt.class))
            return 0L;
 
        classes.add(lcmtypes.mhpc_plan_2D_lcmt.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        for (int a = 0; a < 2; a++) {
            for (int b = 0; b < 100; b++) {
                outs.writeFloat(this.Pos[a][b]); 
            }
        }
 
        for (int a = 0; a < 100; a++) {
            outs.writeFloat(this.rpy[a]); 
        }
 
        for (int a = 0; a < 2; a++) {
            for (int b = 0; b < 100; b++) {
                outs.writeFloat(this.q_knee[a][b]); 
            }
        }
 
        for (int a = 0; a < 2; a++) {
            for (int b = 0; b < 100; b++) {
                outs.writeFloat(this.q_hip[a][b]); 
            }
        }
 
        for (int a = 0; a < 2; a++) {
            for (int b = 0; b < 100; b++) {
                outs.writeFloat(this.Vel[a][b]); 
            }
        }
 
        for (int a = 0; a < 100; a++) {
            outs.writeFloat(this.omega[a]); 
        }
 
        for (int a = 0; a < 2; a++) {
            for (int b = 0; b < 100; b++) {
                outs.writeFloat(this.qd_knee[a][b]); 
            }
        }
 
        for (int a = 0; a < 2; a++) {
            for (int b = 0; b < 100; b++) {
                outs.writeFloat(this.qd_hip[a][b]); 
            }
        }
 
        for (int a = 0; a < 100; a++) {
            outs.writeFloat(this.microtime[a]); 
        }
 
    }
 
    public mhpc_plan_2D_lcmt(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public mhpc_plan_2D_lcmt(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.mhpc_plan_2D_lcmt _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.mhpc_plan_2D_lcmt o = new lcmtypes.mhpc_plan_2D_lcmt();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.Pos = new float[(int) 2][(int) 100];
        for (int a = 0; a < 2; a++) {
            for (int b = 0; b < 100; b++) {
                this.Pos[a][b] = ins.readFloat();
            }
        }
 
        this.rpy = new float[(int) 100];
        for (int a = 0; a < 100; a++) {
            this.rpy[a] = ins.readFloat();
        }
 
        this.q_knee = new float[(int) 2][(int) 100];
        for (int a = 0; a < 2; a++) {
            for (int b = 0; b < 100; b++) {
                this.q_knee[a][b] = ins.readFloat();
            }
        }
 
        this.q_hip = new float[(int) 2][(int) 100];
        for (int a = 0; a < 2; a++) {
            for (int b = 0; b < 100; b++) {
                this.q_hip[a][b] = ins.readFloat();
            }
        }
 
        this.Vel = new float[(int) 2][(int) 100];
        for (int a = 0; a < 2; a++) {
            for (int b = 0; b < 100; b++) {
                this.Vel[a][b] = ins.readFloat();
            }
        }
 
        this.omega = new float[(int) 100];
        for (int a = 0; a < 100; a++) {
            this.omega[a] = ins.readFloat();
        }
 
        this.qd_knee = new float[(int) 2][(int) 100];
        for (int a = 0; a < 2; a++) {
            for (int b = 0; b < 100; b++) {
                this.qd_knee[a][b] = ins.readFloat();
            }
        }
 
        this.qd_hip = new float[(int) 2][(int) 100];
        for (int a = 0; a < 2; a++) {
            for (int b = 0; b < 100; b++) {
                this.qd_hip[a][b] = ins.readFloat();
            }
        }
 
        this.microtime = new float[(int) 100];
        for (int a = 0; a < 100; a++) {
            this.microtime[a] = ins.readFloat();
        }
 
    }
 
    public lcmtypes.mhpc_plan_2D_lcmt copy()
    {
        lcmtypes.mhpc_plan_2D_lcmt outobj = new lcmtypes.mhpc_plan_2D_lcmt();
        outobj.Pos = new float[(int) 2][(int) 100];
        for (int a = 0; a < 2; a++) {
            System.arraycopy(this.Pos[a], 0, outobj.Pos[a], 0, 100);        }
 
        outobj.rpy = new float[(int) 100];
        System.arraycopy(this.rpy, 0, outobj.rpy, 0, 100); 
        outobj.q_knee = new float[(int) 2][(int) 100];
        for (int a = 0; a < 2; a++) {
            System.arraycopy(this.q_knee[a], 0, outobj.q_knee[a], 0, 100);        }
 
        outobj.q_hip = new float[(int) 2][(int) 100];
        for (int a = 0; a < 2; a++) {
            System.arraycopy(this.q_hip[a], 0, outobj.q_hip[a], 0, 100);        }
 
        outobj.Vel = new float[(int) 2][(int) 100];
        for (int a = 0; a < 2; a++) {
            System.arraycopy(this.Vel[a], 0, outobj.Vel[a], 0, 100);        }
 
        outobj.omega = new float[(int) 100];
        System.arraycopy(this.omega, 0, outobj.omega, 0, 100); 
        outobj.qd_knee = new float[(int) 2][(int) 100];
        for (int a = 0; a < 2; a++) {
            System.arraycopy(this.qd_knee[a], 0, outobj.qd_knee[a], 0, 100);        }
 
        outobj.qd_hip = new float[(int) 2][(int) 100];
        for (int a = 0; a < 2; a++) {
            System.arraycopy(this.qd_hip[a], 0, outobj.qd_hip[a], 0, 100);        }
 
        outobj.microtime = new float[(int) 100];
        System.arraycopy(this.microtime, 0, outobj.microtime, 0, 100); 
        return outobj;
    }
 
}

