/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class reset_sim_t implements lcm.lcm.LCMEncodable
{
    public boolean reset;
 
    public reset_sim_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xad85abc8b374b497L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.reset_sim_t.class))
            return 0L;
 
        classes.add(lcmtypes.reset_sim_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeByte( this.reset ? 1 : 0); 
 
    }
 
    public reset_sim_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public reset_sim_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.reset_sim_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.reset_sim_t o = new lcmtypes.reset_sim_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.reset = ins.readByte()!=0;
 
    }
 
    public lcmtypes.reset_sim_t copy()
    {
        lcmtypes.reset_sim_t outobj = new lcmtypes.reset_sim_t();
        outobj.reset = this.reset;
 
        return outobj;
    }
 
}

