/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class vwbc_info_lcmt implements lcm.lcm.LCMEncodable
{
    public float time;
    public int contact_est[];
    public int nWSR;
    public float cputime;
    public int success;
 
    public vwbc_info_lcmt()
    {
        contact_est = new int[4];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x33d64ecddd741edcL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.vwbc_info_lcmt.class))
            return 0L;
 
        classes.add(lcmtypes.vwbc_info_lcmt.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeFloat(this.time); 
 
        for (int a = 0; a < 4; a++) {
            outs.writeInt(this.contact_est[a]); 
        }
 
        outs.writeInt(this.nWSR); 
 
        outs.writeFloat(this.cputime); 
 
        outs.writeInt(this.success); 
 
    }
 
    public vwbc_info_lcmt(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public vwbc_info_lcmt(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.vwbc_info_lcmt _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.vwbc_info_lcmt o = new lcmtypes.vwbc_info_lcmt();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.time = ins.readFloat();
 
        this.contact_est = new int[(int) 4];
        for (int a = 0; a < 4; a++) {
            this.contact_est[a] = ins.readInt();
        }
 
        this.nWSR = ins.readInt();
 
        this.cputime = ins.readFloat();
 
        this.success = ins.readInt();
 
    }
 
    public lcmtypes.vwbc_info_lcmt copy()
    {
        lcmtypes.vwbc_info_lcmt outobj = new lcmtypes.vwbc_info_lcmt();
        outobj.time = this.time;
 
        outobj.contact_est = new int[(int) 4];
        System.arraycopy(this.contact_est, 0, outobj.contact_est, 0, 4); 
        outobj.nWSR = this.nWSR;
 
        outobj.cputime = this.cputime;
 
        outobj.success = this.success;
 
        return outobj;
    }
 
}

