__collection-name__: user-parameter-file

# file_name : "mc-mit-ctrl-user-parameters.yaml"
# file_name : "mhpc-user-parameters.yaml"
# file_name : "c3-jpos-user-parameters.yaml"
# file_name : "imitation-user-parameters.yaml"
file_name : "mhpcll-user-parameters.yaml"