ground-plane:
    type: "infinite-plane"
    mu: 0.6
    restitution: 0.0
    #height: -0.5
    height: 0.0
    graphicsSize: [20,20] # how large the plane appears
    checkers: [40,40]     # how many checkers are on the plane

#mesh-1:
    type: "mesh"
    mu: 0.7
    restitution: 0
    transparent: 1
    #grid: 0.005
    grid: 0.01
    #left_corner_loc: [-6.3, -4.7, 0.07]
    left_corner_loc: [-0.0, -2.2, -0.501]
    #left_corner_loc: [-0.02, -2.2, -0.498]
    heightmap_file: true
    #heightmap_file: false 
    #heightmap_file_name: "heightmap_demo.txt"
    #heightmap_file_name: "heightmap.txt"
    #heightmap_file_name: "../optimization/optimization_data/2019-02-20-13_09_26/HeightMap.txt"
    #heightmap_file_name: "../optimization/optimization_data/2019-02-20-11_11_36/HeightMap.txt"
    #heightmap_file_name: "../optimization/optimization_data/2019-03-03-00_00_00/HeightMap.txt"
    #heightmap_file_name: "../optimization/optimization_data/2019-03-04-00_00_00/heightmap2_fixed.txt"
    #heightmap_file_name: "../optimization/optimization_data/2019-03-05-00_00_01/manual_heightmap.txt"
    #heightmap_file_name: "../optimization/optimization_data/2019-03-05-00_00_02/manual_heightmap.txt"
    #heightmap_file_name: "../optimization/optimization_data/2019-03-05-00_00_03/heightmap.txt"
    heightmap_file_name: "../algorithms/optimization/saved_optimization_data/2019-03-05-00_00_03_2/HeightMap.txt"

# box-1:
    type: "box"
    mu: 0.7
    restitution: 0
    depth: 0.5401
    width: 0.5401
    height: 0.0001
    position:  [0.0, 0, 0.0]
    orientation: [0,.0,0]  # roll pitch yaw
    transparent: 1

# box-2-DoubleJump:
    type: "box"
    mu: 0.7
    restitution: 0
    depth: 0.5401
    width: 0.5401
    height: 0.0001
    position:  [0.64, 0, 0.0]
    orientation: [0,.0,0]  # roll pitch yaw
    transparent: 1

# box-3:
    type: "box"
    mu: 0.7
    restitution: 0
    depth: 0.5401
    width: 0.5401
    height: 0.0001
    position:  [1.28, 0, 0.0]
    orientation: [0,.0,0]  # roll pitch yaw
    transparent: 1

# box-2-BoxJump:
    type: "box"
    mu: 0.7
    restitution: 0
    depth: 0.645
    width: 0.555
    height: 0.14
    position:  [0.6925, 0, 0.07]
    orientation: [0,.0,0]  # roll pitch yaw
    transparent: 1

# box-3-OnBoxOffBox:
    type: "box"
    mu: 0.7
    restitution: 0
    depth: 0.5401
    width: 0.5401
    height: 0.0001
    position:  [1.46, 0, 0.0]
    orientation: [0,.0,0]  # roll pitch yaw
    transparent: 1

box-1-AngledBoxRight:
    type: "box"
    mu: 0.7
    restitution: 0
    depth: 0.7
    width: 0.7
    height: 0.0001
    position:  [0.0, 0, 0.0]
    orientation: [0,.0,0]  # roll pitch yaw
    transparent: 1

box-2-AngledBoxRight:
    type: "box"
    mu: 0.7
    restitution: 0
    depth: 0.65
    width: 0.65
    height: 0.22
    position:  [0.725, -0.3941, 0.0017]
    orientation: [-0.17453,0.0,0]  # roll pitch yaw
    transparent: 0.1

box-3-AngledBoxRight:
    type: "box"
    mu: 0.7
    restitution: 0
    depth: 0.7
    width: 0.7
    height: 0.0001
    position:  [1.45, 0, 0.0]
    orientation: [0,.0,0]  # roll pitch yaw
    transparent: 1


# box-3-AngledToBoxToGround:
    type: "box"
    mu: 0.7
    restitution: 0
    depth: 0.645
    width: 0.555
    height: 0.14
    position:  [1.4225, 0, 0.07]
    orientation: [0,.0,0]  # roll pitch yaw
    transparent: 1

# box-4-AngledToBoxToGround:
    type: "box"
    mu: 0.7
    restitution: 0
    depth: 0.7
    width: 0.7
    height: 0.0001
    position:  [2.145, 0, 0.0]
    orientation: [0,.0,0]  # roll pitch yaw
    transparent: 1

# box-2L-Diamond:
    type: "box"
    mu: 0.7
    restitution: 0
    depth: 0.5401
    width: 0.5401
    height: 0.0001
    position:  [0.64, 0.37, 0.0]
    orientation: [0,.0,0]  # roll pitch yaw
    transparent: 1

# box-2R-Diamond:
    type: "box"
    mu: 0.7
    restitution: 0
    depth: 0.5401
    width: 0.5401
    height: 0.0001
    position:  [0.64, -0.37, 0.0]
    orientation: [0,.0,0]  # roll pitch yaw
    transparent: 1


# obstacle-1:
    type: "box"
    mu: 0.7
    restitution: 0
    depth: 0.01
    width: 0.5401
    height: 0.2
    position:  [0.32, 0, 0.0]
    orientation: [0,.0,0]  # roll pitch yaw
    transparent: 1