__collection-name__: user-parameters

Kp_jointPD:       [100, 50, 50]
Kd_jointPD:       [2, 2, 2]
# angles_jointPD:   [0, -0.7874, 1.7537]
angles_jointPD:   [0, -1.1, 2.2]
draw_plan:        0

Kp_joint:         [3, 3, 3]
Kd_joint:         [1, 0.5, 0.5]

WBC:              2

use_fly_wheels: 1

kick_start:        0.0
kick_dur:          0.0
kick_linear:       [0.0, 0.0, 0.0]
kick_angular:      [0.0, 0.0, 0.0]

vwbc_info_lcm:    0