__collection-name__: user-parameters

Kp_jointPD:       [100, 50, 50]
Kd_jointPD:       [2, 2, 2]
angles_jointPD:   [0, -0.7874, 1.7537]
draw_plan:        0

Kp_joint:         [3, 3, 3]
Kd_joint:         [0.5, 0.5, 0.5]

WBC:              0