# Generated on Mon Aug  5 18:20:08 2019
__collection-name__: user-parameters
kp_joint   :   [150, 4, 4]
kd_joint   :   [5,  1, 1]
home_fleg           : [0, -0.65,1.569]
home_bleg           : [0, -0.6, 1.8]
home_pos            : [0, 0, 0.2565]
home_rpy            : [0,-0.12,0]
n_wbphase:    4
n_fbphase:    4
dt_wb:        0.001
dt_fb:        0.001
cmode:        1
groundH:      -0.404
