"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class mhpc_plan_3D_lcmt(object):
    __slots__ = ["Pos", "rpy", "quat", "q_knee", "q_hip", "v_world", "omega_world", "omega_body", "microtime"]

    __typenames__ = ["float", "float", "float", "float", "float", "float", "float", "float", "float"]

    __dimensions__ = [[3, 100], [3, 100], [4, 100], [4, 100], [4, 100], [3, 100], [3, 100], [3, 100], [100]]

    def __init__(self):
        self.Pos = [ [ 0.0 for dim1 in range(100) ] for dim0 in range(3) ]
        self.rpy = [ [ 0.0 for dim1 in range(100) ] for dim0 in range(3) ]
        self.quat = [ [ 0.0 for dim1 in range(100) ] for dim0 in range(4) ]
        self.q_knee = [ [ 0.0 for dim1 in range(100) ] for dim0 in range(4) ]
        self.q_hip = [ [ 0.0 for dim1 in range(100) ] for dim0 in range(4) ]
        self.v_world = [ [ 0.0 for dim1 in range(100) ] for dim0 in range(3) ]
        self.omega_world = [ [ 0.0 for dim1 in range(100) ] for dim0 in range(3) ]
        self.omega_body = [ [ 0.0 for dim1 in range(100) ] for dim0 in range(3) ]
        self.microtime = [ 0.0 for dim0 in range(100) ]

    def encode(self):
        buf = BytesIO()
        buf.write(mhpc_plan_3D_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        for i0 in range(3):
            buf.write(struct.pack('>100f', *self.Pos[i0][:100]))
        for i0 in range(3):
            buf.write(struct.pack('>100f', *self.rpy[i0][:100]))
        for i0 in range(4):
            buf.write(struct.pack('>100f', *self.quat[i0][:100]))
        for i0 in range(4):
            buf.write(struct.pack('>100f', *self.q_knee[i0][:100]))
        for i0 in range(4):
            buf.write(struct.pack('>100f', *self.q_hip[i0][:100]))
        for i0 in range(3):
            buf.write(struct.pack('>100f', *self.v_world[i0][:100]))
        for i0 in range(3):
            buf.write(struct.pack('>100f', *self.omega_world[i0][:100]))
        for i0 in range(3):
            buf.write(struct.pack('>100f', *self.omega_body[i0][:100]))
        buf.write(struct.pack('>100f', *self.microtime[:100]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != mhpc_plan_3D_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return mhpc_plan_3D_lcmt._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = mhpc_plan_3D_lcmt()
        self.Pos = []
        for i0 in range(3):
            self.Pos.append(struct.unpack('>100f', buf.read(400)))
        self.rpy = []
        for i0 in range(3):
            self.rpy.append(struct.unpack('>100f', buf.read(400)))
        self.quat = []
        for i0 in range(4):
            self.quat.append(struct.unpack('>100f', buf.read(400)))
        self.q_knee = []
        for i0 in range(4):
            self.q_knee.append(struct.unpack('>100f', buf.read(400)))
        self.q_hip = []
        for i0 in range(4):
            self.q_hip.append(struct.unpack('>100f', buf.read(400)))
        self.v_world = []
        for i0 in range(3):
            self.v_world.append(struct.unpack('>100f', buf.read(400)))
        self.omega_world = []
        for i0 in range(3):
            self.omega_world.append(struct.unpack('>100f', buf.read(400)))
        self.omega_body = []
        for i0 in range(3):
            self.omega_body.append(struct.unpack('>100f', buf.read(400)))
        self.microtime = struct.unpack('>100f', buf.read(400))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if mhpc_plan_3D_lcmt in parents: return 0
        tmphash = (0x7466efdedbbbab26) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if mhpc_plan_3D_lcmt._packed_fingerprint is None:
            mhpc_plan_3D_lcmt._packed_fingerprint = struct.pack(">Q", mhpc_plan_3D_lcmt._get_hash_recursive([]))
        return mhpc_plan_3D_lcmt._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", mhpc_plan_3D_lcmt._get_packed_fingerprint())[0]

