"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class reset_sim_t(object):
    __slots__ = ["reset"]

    __typenames__ = ["boolean"]

    __dimensions__ = [None]

    def __init__(self):
        self.reset = False

    def encode(self):
        buf = BytesIO()
        buf.write(reset_sim_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">b", self.reset))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != reset_sim_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return reset_sim_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = reset_sim_t()
        self.reset = bool(struct.unpack('b', buf.read(1))[0])
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if reset_sim_t in parents: return 0
        tmphash = (0xad85abc8b374b497) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if reset_sim_t._packed_fingerprint is None:
            reset_sim_t._packed_fingerprint = struct.pack(">Q", reset_sim_t._get_hash_recursive([]))
        return reset_sim_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", reset_sim_t._get_packed_fingerprint())[0]

