"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class vwbc_info_lcmt(object):
    __slots__ = ["time", "contact_est", "nWSR", "cputime", "success"]

    __typenames__ = ["float", "int32_t", "int32_t", "float", "int32_t"]

    __dimensions__ = [None, [4], None, None, None]

    def __init__(self):
        self.time = 0.0
        self.contact_est = [ 0 for dim0 in range(4) ]
        self.nWSR = 0
        self.cputime = 0.0
        self.success = 0

    def encode(self):
        buf = BytesIO()
        buf.write(vwbc_info_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">f", self.time))
        buf.write(struct.pack('>4i', *self.contact_est[:4]))
        buf.write(struct.pack(">ifi", self.nWSR, self.cputime, self.success))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != vwbc_info_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return vwbc_info_lcmt._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = vwbc_info_lcmt()
        self.time = struct.unpack(">f", buf.read(4))[0]
        self.contact_est = struct.unpack('>4i', buf.read(16))
        self.nWSR, self.cputime, self.success = struct.unpack(">ifi", buf.read(12))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if vwbc_info_lcmt in parents: return 0
        tmphash = (0x33d64ecddd741edc) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if vwbc_info_lcmt._packed_fingerprint is None:
            vwbc_info_lcmt._packed_fingerprint = struct.pack(">Q", vwbc_info_lcmt._get_hash_recursive([]))
        return vwbc_info_lcmt._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", vwbc_info_lcmt._get_packed_fingerprint())[0]

