/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

extern "C" int footAcc(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int footAcc_alloc_mem(void);
extern "C" int footAcc_init_mem(int mem);
extern "C" void footAcc_free_mem(int mem);
extern "C" int footAcc_checkout(void);
extern "C" void footAcc_release(int mem);
extern "C" void footAcc_incref(void);
extern "C" void footAcc_decref(void);
extern "C" casadi_int footAcc_n_out(void);
extern "C" casadi_int footAcc_n_in(void);
extern "C" casadi_real footAcc_default_in(casadi_int i);
extern "C" const char* footAcc_name_in(casadi_int i);
extern "C" const char* footAcc_name_out(casadi_int i);
extern "C" const casadi_int* footAcc_sparsity_in(casadi_int i);
extern "C" const casadi_int* footAcc_sparsity_out(casadi_int i);
extern "C" int footAcc_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int footJacobian(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int footJacobian_alloc_mem(void);
extern "C" int footJacobian_init_mem(int mem);
extern "C" void footJacobian_free_mem(int mem);
extern "C" int footJacobian_checkout(void);
extern "C" void footJacobian_release(int mem);
extern "C" void footJacobian_incref(void);
extern "C" void footJacobian_decref(void);
extern "C" casadi_int footJacobian_n_out(void);
extern "C" casadi_int footJacobian_n_in(void);
extern "C" casadi_real footJacobian_default_in(casadi_int i);
extern "C" const char* footJacobian_name_in(casadi_int i);
extern "C" const char* footJacobian_name_out(casadi_int i);
extern "C" const casadi_int* footJacobian_sparsity_in(casadi_int i);
extern "C" const casadi_int* footJacobian_sparsity_out(casadi_int i);
extern "C" int footJacobian_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
